# -*- coding: utf-8 -*-
"""01_github_commit_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2WJqs3VRjcUyWjJs9IZNqvBpj8l6aCj
"""

import requests
import pandas as pd
import time

GITHUB_TOKEN = "PLACEHOLDER"

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

OWNER = "pallets"
REPO = "flask"

url = f"https://api.github.com/repos/{OWNER}/{REPO}/commits?per_page=100"
response = requests.get(url, headers=HEADERS)

print("Status code:", response.status_code)

commits = response.json()
print("Number of commits fetched:", len(commits))

all_commits = []
page = 1

while len(all_commits) < 300:
    url = f"https://api.github.com/repos/{OWNER}/{REPO}/commits?per_page=100&page={page}"
    response = requests.get(url, headers=HEADERS)

    if response.status_code != 200:
        print("Error fetching commits")
        break

    batch = response.json()
    if not batch:
        break

    all_commits.extend(batch)
    page += 1
    time.sleep(0.2)

commits = all_commits[:300]

print("Total commits collected:", len(commits))

detailed_commit_data = []

for i, c in enumerate(commits):
    sha = c.get("sha", "")
    detail_url = f"https://api.github.com/repos/{OWNER}/{REPO}/commits/{sha}"

    detail_response = requests.get(detail_url, headers=HEADERS)

    if detail_response.status_code != 200:
        print(f"Failed for {sha}")
        continue

    detail = detail_response.json()

    commit_info = detail.get("commit", {})
    author_info = commit_info.get("author", {})
    stats = detail.get("stats", {})
    files = detail.get("files", [])


    message = commit_info.get("message", "")
    author = author_info.get("name", "Unknown")
    date = author_info.get("date", "")

    additions = stats.get("additions", 0)
    deletions = stats.get("deletions", 0)
    total_changes = stats.get("total", 0)
    files_changed = len(files)

    file_types = [f["filename"].split(".")[-1] for f in files if "." in f["filename"]]
    py_files = sum(1 for f in file_types if f == "py")
    core_code_ratio = py_files / len(file_types) if len(file_types) > 0 else 0

    detailed_commit_data.append({
        "sha": sha,
        "message": message,
        "author": author,
        "date": date,
        "additions": additions,
        "deletions": deletions,
        "total_changes": total_changes,
        "files_changed": files_changed,
        "core_code_ratio": core_code_ratio
    })

    print(f"Done {i+1}/{len(commits)}")
    time.sleep(0.2)

file_types = [f["filename"].split(".")[-1] for f in files if "." in f["filename"]]

py_files = sum(1 for f in file_types if f == "py")

core_code_ratio = py_files / len(file_types) if len(file_types) > 0 else 0

df = pd.DataFrame(detailed_commit_data)
df.head()

df = df.drop_duplicates(subset=["sha"]).copy()

df["message"] = df["message"].fillna("")
df["author"] = df["author"].fillna("Unknown")
df["date"] = df["date"].fillna("")

df.info()

df["message_lower"] = df["message"].str.lower()
df["message_length"] = df["message"].apply(len)

bug_words = ["fix", "bug", "error", "issue", "patch", "hotfix"]
urgent_words = ["urgent", "quick", "temporary", "workaround"]

df["has_fix_word"] = df["message_lower"].apply(
    lambda x: 1 if any(word in x for word in bug_words) else 0
)

df["has_urgent_word"] = df["message_lower"].apply(
    lambda x: 1 if any(word in x for word in urgent_words) else 0
)

df[["message", "message_length", "has_fix_word", "has_urgent_word"]].head()

df["large_commit"] = (df["total_changes"] > df["total_changes"].median()).astype(int)
df["multi_file_commit"] = (df["files_changed"] > 1).astype(int)

df[["total_changes", "files_changed", "large_commit", "multi_file_commit"]].head()

def is_bug_fix(msg):
    bug_words = ["fix", "bug", "error", "issue", "patch", "hotfix"]
    msg = str(msg).lower()
    return any(word in msg for word in bug_words)

# NOTE:
# The label is a heuristic approximation.
# A commit is marked as risky (1) if a bug-fix related commit appears
# within the next 'window' commits.
# This does NOT represent actual bug data, but serves as a proxy signal.

df["future_bug"] = 0
window = 3

messages = df["message"].fillna("").str.lower().tolist()
for i in range(len(df)):
    for j in range(1, window + 1):
        if i + j < len(df):
            if is_bug_fix(messages[i + j]):
                df.at[i, "future_bug"] = 1
                break

df["label"] = df["future_bug"].astype(int)

df["date"] = pd.to_datetime(df["date"], errors="coerce")

df = df.sort_values(by="date").reset_index(drop=True)

df["hour"] = df["date"].dt.hour
df["day_of_week"] = df["date"].dt.dayofweek

author_commit_counts = df["author"].value_counts().to_dict()  #author experience
df["author_experience"] = df["author"].map(author_commit_counts)

df["is_new_contributor"] = (df["author_experience"] < 3).astype(int)

df["time_since_last_commit"] = df["date"].diff().dt.total_seconds().fillna(0)  #time since last commit

df["is_late_night"] = ((df["hour"] >= 22) | (df["hour"] <= 5)).astype(int)  #late night commits

df["rolling_changes"] = df["total_changes"].rolling(5).mean().fillna(0)  #change spike
df["change_spike"] = (df["total_changes"] > df["rolling_changes"] * 2).astype(int)

final_df = df[
    [
        "sha",
        "message",
        "author",
        "date",
        "additions",
        "deletions",
        "total_changes",
        "files_changed",
        "hour",
        "day_of_week",
        "message_length",
        "has_fix_word",
        "has_urgent_word",
        "large_commit",
        "multi_file_commit",
        "label",
        "author_experience",
        "is_new_contributor",
        "time_since_last_commit",
        "is_late_night",
        "change_spike",
        "core_code_ratio"
    ]
].copy()

final_df.to_csv("commits_dataset.csv", index=False)

print("Saved successfully as commits_dataset.csv")
print("Shape:", final_df.shape)
print(final_df["label"].value_counts())

from google.colab import files
files.download("commits_dataset.csv")