# -*- coding: utf-8 -*-
"""02_commit_risk_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkjkJZtTfAzzmBk7b43gzD9ZpFliXUtJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack, csr_matrix
from sklearn.metrics import roc_auc_score

df = pd.read_csv("commits_dataset.csv")
df.head()

print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nMissing values:")
print(df.isnull().sum())

print("\nLabel distribution:")
print(df["label"].value_counts())
print("\nLabel distribution (proportion):")
print(df["label"].value_counts(normalize=True))

features = [
    "additions",
    "deletions",
    "total_changes",
    "files_changed",
    "hour",
    "day_of_week",
    "message_length",
    "has_fix_word",
    "has_urgent_word",
    "large_commit",
    "multi_file_commit",
    "author_experience",
    "is_new_contributor",
    "time_since_last_commit",
    "is_late_night",
    "change_spike",
    "core_code_ratio"
]

tfidf = TfidfVectorizer(max_features=100)
X_text = tfidf.fit_transform(df["message"])

X_numeric = df[features].fillna(0)
X_numeric_sparse = csr_matrix(X_numeric.values)

X = hstack([X_numeric_sparse, X_text])
y = df["label"]
print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train distribution:")
print(y_train.value_counts())
print("y_test distribution:")
print(y_test.value_counts())

log_reg_pipeline = Pipeline([
    ("model", LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced"))
])

rf_pipeline = Pipeline([
    ("model", RandomForestClassifier(random_state=42, n_estimators=200, class_weight="balanced"))
])

gb_pipeline = Pipeline([
    ("model", GradientBoostingClassifier(random_state=42))
])

models = {
    "Logistic Regression": log_reg_pipeline,
    "Random Forest": rf_pipeline,
    "Gradient Boosting": gb_pipeline
}

from xgboost import XGBClassifier

xgb_pipeline = Pipeline([
    ("model", XGBClassifier(eval_metric="logloss"))
])

models["XGBoost"] = xgb_pipeline

for name, model in models.items():
    model.fit(X_train, y_train)
    print(f"{name} trained successfully.")

results = []

for name, model in models.items():
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1 Score": f1_score(y_test, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test, y_proba)
    })

for name, model in models.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred, zero_division=0))

for name, model in models.items():
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    plt.title(f"Confusion Matrix - {name}")
    plt.show()

results_df = pd.DataFrame(results).sort_values(by="F1 Score", ascending=False)

best_model_name = results_df.iloc[0]["Model"]
best_model = models[best_model_name]

print("Best model based on F1 Score:", best_model_name)

print("\nTop important features (Random Forest):")

rf_model = models["Random Forest"].named_steps["model"]
importances = rf_model.feature_importances_

# combine feature names
tfidf_features = tfidf.get_feature_names_out()
all_features = list(features) + list(tfidf_features)

importance_df = pd.DataFrame({
    "feature": all_features,
    "importance": importances
}).sort_values(by="importance", ascending=False)

print(importance_df.head(15))

y_test_pred = best_model.predict(X_test)

prediction_df = pd.DataFrame(y_test).copy()
prediction_df["predicted_label"] = y_test_pred
prediction_df.rename(columns={"label": "actual_label"}, inplace=True)
prediction_df["actual_label"] = y_test.values
prediction_df["predicted_label"] = y_test_pred

prediction_df.head(10)

wrong_predictions = prediction_df[prediction_df["actual_label"] != prediction_df["predicted_label"]]
print("Number of wrong predictions:", len(wrong_predictions))
wrong_predictions

results_df.to_csv("model_comparison_results.csv", index=False)
print("Saved model comparison results.")

import joblib

joblib.dump(best_model, "best_commit_risk_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model + TF-IDF saved")

from google.colab import files
files.download("best_commit_risk_model.pkl")
files.download("tfidf_vectorizer.pkl")